// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://indfljlbpamrinjaxmeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZGZsamxicGFtcmluamF4bWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTg5MjIsImV4cCI6MjA2MDEzNDkyMn0.NASu2wiram8N4wGQdToqvccxMIXL5ygtO49_DPByywU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);